import type { LivePublication } from './types';

export const MOCK_LIVE_PUBLICATIONS: LivePublication[] = [
  {
    id: '1',
    title: 'Новогодние игрушки 2026 — розыгрыш среди сотрудников',
    description:
      'Количество игрушек ограничено, поэтому обладателей выберем случайным образом среди всех желающих. Участвуйте в розыгрыше до конца недели!',
    imageUrl: '',
    authorName: 'Корп. культура',
    publishedAt: '2026-02-10T12:00:00Z',
    likesCount: 27,
    heartsCount: 3,
    viewsCount: 507,
    commentsCount: 45,
    tags: ['розыгрыш', 'новый год'],
    category: 'corporate',
    isPinned: true,
  },
  {
    id: '2',
    title: 'Забег РФ ЗАБЕГ — праздник для всех любителей бега',
    description:
      'Десятый всероссийский полумарафон с синхронным стартом. Присоединяйтесь к команде МЕДИПАЛ и пробегите дистанцию вместе с коллегами!',
    imageUrl: '',
    authorName: 'Спорт',
    publishedAt: '2026-02-08T09:00:00Z',
    likesCount: 19,
    heartsCount: 0,
    viewsCount: 204,
    commentsCount: 8,
    tags: ['спорт', 'забег', 'полумарафон'],
    category: 'sport',
  },
  {
    id: '3',
    title: 'Мастер-класс по акварели — открыта запись',
    description:
      'Приглашаем на творческий мастер-класс по акварельной живописи. Все материалы предоставляются. Количество мест ограничено — записывайтесь заранее.',
    imageUrl: '',
    authorName: 'Творческий клуб',
    publishedAt: '2026-02-15T14:00:00Z',
    likesCount: 34,
    heartsCount: 12,
    viewsCount: 312,
    commentsCount: 21,
    tags: ['творчество', 'мастер-класс', 'акварель'],
    category: 'creative',
  },
  {
    id: '4',
    title: 'Волонтёрская акция «Добрые руки» — помощь приюту',
    description:
      'Собираем корма и игрушки для животных из приюта «Дружок». Пункт сбора — 3 этаж, ресепшн. Акция продлится до конца февраля.',
    imageUrl: '',
    authorName: 'Волонтёры МЕДИПАЛ',
    publishedAt: '2026-02-12T10:00:00Z',
    likesCount: 56,
    heartsCount: 28,
    viewsCount: 890,
    commentsCount: 32,
    tags: ['волонтёрство', 'приют', 'животные'],
    category: 'volunteer',
  },
  {
    id: '5',
    title: 'День рождения компании — программа празднования',
    description:
      'В этом году нашей компании исполняется 15 лет! Подготовили насыщенную программу: квиз, фуршет, розыгрыш призов и выступление кавер-группы.',
    imageUrl: '',
    authorName: 'HR-отдел',
    publishedAt: '2026-02-18T08:00:00Z',
    likesCount: 89,
    heartsCount: 41,
    viewsCount: 1240,
    commentsCount: 67,
    tags: ['мероприятие', 'юбилей', 'праздник'],
    category: 'events',
    isPinned: true,
  },
  {
    id: '6',
    title: 'Турнир по настольному теннису — финал в пятницу',
    description:
      'Полуфинальные матчи прошли, определились финалисты! Приглашаем всех болельщиков поддержать участников в пятницу в 17:00 в спортзале.',
    imageUrl: '',
    authorName: 'Спорт',
    publishedAt: '2026-02-17T11:00:00Z',
    likesCount: 15,
    heartsCount: 2,
    viewsCount: 178,
    commentsCount: 12,
    tags: ['спорт', 'теннис', 'турнир'],
    category: 'sport',
  },
  {
    id: '7',
    title: 'Фотоконкурс «Зимние пейзажи» — голосование открыто',
    description:
      'Все работы загружены! Голосуйте за лучший зимний снимок наших коллег. Автор-победитель получит сертификат на фотосессию.',
    imageUrl: '',
    authorName: 'Творческий клуб',
    publishedAt: '2026-02-14T16:00:00Z',
    likesCount: 42,
    heartsCount: 18,
    viewsCount: 654,
    commentsCount: 29,
    tags: ['творчество', 'фото', 'конкурс'],
    category: 'creative',
  },
  {
    id: '8',
    title: 'Благотворительная ярмарка — 28 февраля',
    description:
      'Приносите handmade-изделия, выпечку и сувениры на благотворительную ярмарку. Все вырученные средства пойдут в фонд помощи детям.',
    imageUrl: '',
    authorName: 'Волонтёры МЕДИПАЛ',
    publishedAt: '2026-02-16T13:00:00Z',
    likesCount: 73,
    heartsCount: 35,
    viewsCount: 920,
    commentsCount: 41,
    tags: ['благотворительность', 'ярмарка'],
    category: 'volunteer',
  },
  {
    id: '9',
    title: 'Вебинар: эмоциональный интеллект в работе',
    description:
      'Спикер — бизнес-психолог Анна Кравцова. Узнайте, как управлять эмоциями на рабочем месте и выстраивать продуктивные отношения с коллегами.',
    imageUrl: '',
    authorName: 'Корп. культура',
    publishedAt: '2026-02-19T09:00:00Z',
    likesCount: 31,
    heartsCount: 7,
    viewsCount: 445,
    commentsCount: 14,
    tags: ['вебинар', 'развитие', 'психология'],
    category: 'corporate',
  },
  {
    id: '10',
    title: 'Квиз «Что? Где? Когда?» — набор команд',
    description:
      'Формируйте команды по 4-6 человек и регистрируйтесь на корпоративный квиз! Призы для первых трёх мест и специальная номинация «Самая дружная команда».',
    imageUrl: '',
    authorName: 'HR-отдел',
    publishedAt: '2026-02-13T15:00:00Z',
    likesCount: 48,
    heartsCount: 9,
    viewsCount: 567,
    commentsCount: 38,
    tags: ['мероприятие', 'квиз', 'команда'],
    category: 'events',
  },
];

export const LIVE_STATS = {
  totalPublications: 156,
  thisMonth: 24,
  totalAuthors: 42,
  totalReactions: 3420,
};
