import type { TeamMember, TeamStats } from './types';

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: '1',
    fullName: 'Сидоров Алексей Петрович',
    position: 'Генеральный директор',
    department: 'management',
    email: 'sidorov@company.ru',
    phone: '+7 (495) 123-45-01',
    hireDate: '2018-03-15',
    location: 'Москва, Центральный офис',
    isOnline: true,
    tags: ['руководство', 'стратегия'],
  },
  {
    id: '2',
    fullName: 'Назаров Николай Андреевич',
    position: 'Системный администратор',
    department: 'it',
    email: 'nazarov@company.ru',
    phone: '+7 (495) 123-45-02',
    hireDate: '2022-06-01',
    location: 'Москва, Центральный офис',
    isOnline: true,
    tags: ['инфраструктура', 'сервера'],
  },
  {
    id: '3',
    fullName: 'Иванова Мария Сергеевна',
    position: 'HR-директор',
    department: 'hr',
    email: 'ivanova@company.ru',
    phone: '+7 (495) 123-45-03',
    hireDate: '2019-09-10',
    location: 'Москва, Центральный офис',
    isOnline: false,
    tags: ['подбор', 'обучение', 'адаптация'],
  },
  {
    id: '4',
    fullName: 'Петров Дмитрий Александрович',
    position: 'Ведущий разработчик',
    department: 'it',
    email: 'petrov@company.ru',
    hireDate: '2021-01-20',
    location: 'Москва, Центральный офис',
    isOnline: true,
    tags: ['frontend', 'react', 'typescript'],
  },
  {
    id: '5',
    fullName: 'Козлова Анна Викторовна',
    position: 'Главный бухгалтер',
    department: 'finance',
    email: 'kozlova@company.ru',
    phone: '+7 (495) 123-45-05',
    hireDate: '2020-04-15',
    location: 'Москва, Центральный офис',
    isOnline: false,
    tags: ['бухгалтерия', 'отчётность'],
  },
  {
    id: '6',
    fullName: 'Тарасов Сергей Анатольевич',
    position: 'Менеджер интернет-продаж',
    department: 'sales',
    email: 'tarasov@company.ru',
    hireDate: '2026-02-18',
    location: 'Москва, Центральный офис',
    isOnline: true,
    tags: ['продажи', 'e-commerce'],
  },
  {
    id: '7',
    fullName: 'Борискин Иван Игоревич',
    position: 'Инженер технической поддержки',
    department: 'support',
    email: 'boriskin@company.ru',
    hireDate: '2025-02-24',
    location: 'Москва, Центральный офис',
    isOnline: false,
    tags: ['поддержка', 'оборудование'],
  },
  {
    id: '8',
    fullName: 'Смирнова Ольга Дмитриевна',
    position: 'Менеджер по логистике',
    department: 'logistics',
    email: 'smirnova@company.ru',
    hireDate: '2023-07-01',
    location: 'Москва, Склад',
    isOnline: true,
    tags: ['склад', 'доставка'],
  },
  {
    id: '9',
    fullName: 'Ляхов Алексей Федорович',
    position: 'Системный аналитик',
    department: 'it',
    email: 'lyahov@company.ru',
    hireDate: '2022-11-15',
    location: 'Москва, Центральный офис',
    isOnline: true,
    tags: ['аналитика', 'бизнес-процессы'],
  },
  {
    id: '10',
    fullName: 'Битяй Елена Анатольевна',
    position: 'Специалист по подбору персонала',
    department: 'hr',
    email: 'bityay@company.ru',
    hireDate: '2024-03-01',
    location: 'Москва, Центральный офис',
    isOnline: false,
    tags: ['рекрутинг', 'собеседования'],
  },
  {
    id: '11',
    fullName: 'Федорова Екатерина Андреевна',
    position: 'Финансовый аналитик',
    department: 'finance',
    email: 'fedorova@company.ru',
    hireDate: '2023-09-15',
    location: 'Москва, Центральный офис',
    isOnline: true,
    tags: ['финансы', 'аналитика'],
  },
  {
    id: '12',
    fullName: 'Григорьев Максим Олегович',
    position: 'Руководитель отдела продаж',
    department: 'sales',
    email: 'grigoriev@company.ru',
    phone: '+7 (495) 123-45-12',
    hireDate: '2020-08-01',
    location: 'Москва, Центральный офис',
    isOnline: true,
    tags: ['продажи', 'управление'],
  },
];

export const TEAM_STATS: TeamStats = {
  totalEmployees: 247,
  departments: 8,
  newThisMonth: 3,
};
