import type { MerchProduct, MerchShopStats, UserBalance } from './types';

export const MOCK_MERCH_PRODUCTS: MerchProduct[] = [
  {
    id: '1',
    name: 'Худи «Медипал» с вышитым логотипом',
    description:
      'Мягкое утеплённое худи из органического хлопка с вышитым логотипом компании на груди. Идеально для офиса и прогулок.',
    category: 'clothing',
    priceCoins: 850,
    rating: 4.9,
    reviewsCount: 38,
    soldCount: 124,
    inStock: true,
    stockCount: 45,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['#1e293b', '#f8fafc', '#0d9488'],
    isBestseller: true,
    tags: ['худи', 'одежда', 'лого'],
    addedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Термокружка «Медипал» 350 мл',
    description:
      'Стильная термокружка из нержавеющей стали с покрытием soft-touch и гравировкой логотипа. Держит тепло до 6 часов.',
    category: 'drinkware',
    priceCoins: 320,
    oldPriceCoins: 400,
    rating: 4.7,
    reviewsCount: 52,
    soldCount: 210,
    inStock: true,
    stockCount: 78,
    colors: ['#1e293b', '#f8fafc', '#0d9488'],
    isBestseller: true,
    tags: ['кружка', 'термос', 'офис'],
    addedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: '3',
    name: 'Блокнот A5 «Медипал» в кожаном переплёте',
    description:
      'Премиальный блокнот формата A5 с тиснением логотипа. 192 страницы в линейку, закладка-ляссе, петля для ручки.',
    category: 'stationery',
    priceCoins: 250,
    rating: 4.8,
    reviewsCount: 67,
    soldCount: 340,
    inStock: true,
    stockCount: 120,
    colors: ['#1e293b', '#7c3aed'],
    isNew: false,
    isBestseller: true,
    tags: ['блокнот', 'канцелярия', 'кожа'],
    addedAt: '2025-12-20T10:00:00Z',
  },
  {
    id: '4',
    name: 'Футболка «Медипал» — лимитированная серия',
    description:
      'Футболка из 100% хлопка с уникальным дизайном к юбилею компании. Ограниченный тираж — всего 100 штук.',
    category: 'clothing',
    priceCoins: 450,
    rating: 4.9,
    reviewsCount: 15,
    soldCount: 67,
    inStock: true,
    stockCount: 33,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['#f8fafc', '#1e293b'],
    isNew: true,
    isLimited: true,
    tags: ['футболка', 'лимитка', 'юбилей'],
    addedAt: '2026-02-28T10:00:00Z',
  },
  {
    id: '5',
    name: 'Рюкзак «Медипал» для ноутбука',
    description:
      'Городской рюкзак с отделением для ноутбука до 15.6". Влагозащитная ткань, USB-порт, светоотражающие элементы.',
    category: 'accessories',
    priceCoins: 1200,
    rating: 4.6,
    reviewsCount: 23,
    soldCount: 48,
    inStock: true,
    stockCount: 15,
    colors: ['#1e293b', '#334155'],
    tags: ['рюкзак', 'ноутбук', 'сумка'],
    addedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: '6',
    name: 'Беспроводные наушники с логотипом',
    description:
      'TWS-наушники с активным шумоподавлением и кейсом с лазерной гравировкой логотипа. До 24 часов работы.',
    category: 'tech',
    priceCoins: 1500,
    rating: 4.5,
    reviewsCount: 18,
    soldCount: 31,
    inStock: true,
    stockCount: 22,
    colors: ['#f8fafc', '#1e293b'],
    isNew: true,
    tags: ['наушники', 'техника', 'bluetooth'],
    addedAt: '2026-03-01T10:00:00Z',
  },
  {
    id: '7',
    name: 'Набор ручек «Медипал» (3 шт.)',
    description:
      'Комплект из трёх гелевых ручек в фирменных цветах с гравировкой. Металлический корпус, мягкий ход.',
    category: 'stationery',
    priceCoins: 150,
    rating: 4.4,
    reviewsCount: 42,
    soldCount: 280,
    inStock: true,
    stockCount: 200,
    tags: ['ручки', 'канцелярия', 'набор'],
    addedAt: '2025-11-15T10:00:00Z',
  },
  {
    id: '8',
    name: 'Подарочный набор «Новичок»',
    description:
      'Всё для комфортного старта: термокружка, блокнот, ручка и стикеры в фирменной коробке.',
    category: 'gift-sets',
    priceCoins: 600,
    oldPriceCoins: 750,
    rating: 4.9,
    reviewsCount: 89,
    soldCount: 156,
    inStock: true,
    stockCount: 40,
    tags: ['подарок', 'набор', 'онбординг'],
    addedAt: '2026-01-05T10:00:00Z',
  },
  {
    id: '9',
    name: 'Керамическая кружка «Медипал» 300 мл',
    description:
      'Классическая керамическая кружка с двусторонней печатью логотипа. Можно мыть в посудомоечной машине.',
    category: 'drinkware',
    priceCoins: 120,
    rating: 4.3,
    reviewsCount: 95,
    soldCount: 450,
    inStock: true,
    stockCount: 300,
    colors: ['#f8fafc', '#0d9488'],
    tags: ['кружка', 'керамика', 'офис'],
    addedAt: '2025-10-10T10:00:00Z',
  },
  {
    id: '10',
    name: 'Power Bank «Медипал» 10000 мАч',
    description:
      'Портативная батарея с лазерной гравировкой. Два USB-выхода + USB-C, быстрая зарядка QC 3.0.',
    category: 'tech',
    priceCoins: 700,
    rating: 4.7,
    reviewsCount: 29,
    soldCount: 73,
    inStock: true,
    stockCount: 35,
    colors: ['#1e293b', '#f8fafc'],
    tags: ['powerbank', 'зарядка', 'техника'],
    addedAt: '2026-02-10T10:00:00Z',
  },
  {
    id: '11',
    name: 'Шоппер «Медипал» — эко-сумка',
    description:
      'Плотная хлопковая сумка-шоппер с принтом. Внутренний карман на молнии, укреплённые ручки.',
    category: 'accessories',
    priceCoins: 180,
    rating: 4.6,
    reviewsCount: 34,
    soldCount: 190,
    inStock: true,
    stockCount: 85,
    colors: ['#fef3c7', '#1e293b'],
    tags: ['сумка', 'эко', 'шоппер'],
    addedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: '12',
    name: 'Подарочный набор «Premium»',
    description:
      'Премиальный набор: худи, термокружка, блокнот в кожаном переплёте и набор стикеров в фирменной упаковке.',
    category: 'gift-sets',
    priceCoins: 1800,
    oldPriceCoins: 2200,
    rating: 5.0,
    reviewsCount: 12,
    soldCount: 28,
    inStock: true,
    stockCount: 10,
    isLimited: true,
    isNew: true,
    tags: ['подарок', 'премиум', 'набор'],
    addedAt: '2026-03-05T10:00:00Z',
  },
];

export const MERCH_SHOP_STATS: MerchShopStats = {
  totalProducts: 42,
  categories: 6,
  soldThisMonth: 187,
};

export const USER_BALANCE: UserBalance = {
  coins: 2450,
  pendingCoins: 300,
};
