import type { KBDocument, KBCategoryInfo, KBStats } from './types';

export const KB_CATEGORIES: KBCategoryInfo[] = [
  {
    key: 'regulations',
    label: 'Регламенты',
    icon: 'GavelRounded',
    color: '#6366f1',
    description: 'Внутренние регламенты, стандарты и нормативные документы компании',
    count: 24,
  },
  {
    key: 'instructions',
    label: 'Инструкции',
    icon: 'AssignmentRounded',
    color: '#0d9488',
    description: 'Пошаговые руководства по работе с системами и процессами',
    count: 38,
  },
  {
    key: 'templates',
    label: 'Шаблоны',
    icon: 'DescriptionRounded',
    color: '#f59e0b',
    description: 'Готовые шаблоны документов, отчётов и заявлений',
    count: 19,
  },
  {
    key: 'policies',
    label: 'Политики',
    icon: 'ShieldRounded',
    color: '#ef4444',
    description: 'Политики безопасности, конфиденциальности и корпоративные правила',
    count: 12,
  },
  {
    key: 'onboarding',
    label: 'Онбординг',
    icon: 'SchoolRounded',
    color: '#3b82f6',
    description: 'Материалы для адаптации новых сотрудников',
    count: 15,
  },
  {
    key: 'faq',
    label: 'FAQ',
    icon: 'HelpOutlineRounded',
    color: '#8b5cf6',
    description: 'Часто задаваемые вопросы и ответы',
    count: 31,
  },
];

export const MOCK_DOCUMENTS: KBDocument[] = [
  {
    id: 'doc-1',
    title: 'Регламент согласования договоров',
    description:
      'Порядок подготовки, согласования и подписания договоров с контрагентами. Включает маршруты согласования и сроки.',
    category: 'regulations',
    department: 'Юридический отдел',
    author: 'Смирнова Е.А.',
    status: 'active',
    viewCount: 342,
    downloadCount: 128,
    fileType: 'pdf',
    fileSize: '1.2 МБ',
    tags: ['договоры', 'согласование', 'юридический'],
    isPinned: true,
    updatedAt: '2026-03-08T10:00:00Z',
    createdAt: '2025-06-15T10:00:00Z',
    source1C: 'Документооборот.Регламенты',
  },
  {
    id: 'doc-2',
    title: 'Инструкция по работе с 1С:Документооборот',
    description:
      'Подробное руководство по основным операциям в системе 1С:Документооборот — создание, согласование и отправка документов.',
    category: 'instructions',
    department: 'IT-отдел',
    author: 'Козлов Д.В.',
    status: 'active',
    viewCount: 567,
    downloadCount: 234,
    fileType: 'pdf',
    fileSize: '3.8 МБ',
    tags: ['1С', 'документооборот', 'руководство'],
    isPinned: true,
    isNew: true,
    updatedAt: '2026-03-10T08:00:00Z',
    createdAt: '2026-02-01T10:00:00Z',
    source1C: 'Инструкции.1С',
  },
  {
    id: 'doc-3',
    title: 'Шаблон заявления на отпуск',
    description:
      'Унифицированный шаблон заявления на ежегодный оплачиваемый отпуск для сотрудников.',
    category: 'templates',
    department: 'HR-отдел',
    author: 'Петрова М.С.',
    status: 'active',
    viewCount: 891,
    downloadCount: 456,
    fileType: 'docx',
    fileSize: '45 КБ',
    tags: ['отпуск', 'заявление', 'HR'],
    updatedAt: '2026-02-20T10:00:00Z',
    createdAt: '2025-01-10T10:00:00Z',
    source1C: 'Шаблоны.HR',
  },
  {
    id: 'doc-4',
    title: 'Политика информационной безопасности',
    description:
      'Основные правила и требования по обеспечению информационной безопасности в компании. Обязательна к ознакомлению для всех сотрудников.',
    category: 'policies',
    department: 'Служба безопасности',
    author: 'Иванов А.П.',
    status: 'active',
    viewCount: 1203,
    downloadCount: 89,
    fileType: 'pdf',
    fileSize: '2.1 МБ',
    tags: ['безопасность', 'ИБ', 'обязательное'],
    isPinned: true,
    updatedAt: '2026-01-15T10:00:00Z',
    createdAt: '2024-09-01T10:00:00Z',
    source1C: 'Политики.ИБ',
  },
  {
    id: 'doc-5',
    title: 'Гайд для нового сотрудника',
    description:
      'Всё, что нужно знать в первые рабочие дни: от получения пропуска до настройки рабочего окружения и знакомства с командой.',
    category: 'onboarding',
    department: 'HR-отдел',
    author: 'Петрова М.С.',
    status: 'active',
    viewCount: 678,
    downloadCount: 312,
    fileType: 'pdf',
    fileSize: '5.4 МБ',
    tags: ['онбординг', 'новый сотрудник', 'адаптация'],
    isNew: true,
    updatedAt: '2026-03-05T10:00:00Z',
    createdAt: '2026-02-15T10:00:00Z',
    source1C: 'Онбординг.Материалы',
  },
  {
    id: 'doc-6',
    title: 'Как подключить VPN?',
    description:
      'Пошаговая инструкция по настройке VPN-подключения для удалённой работы. Поддерживаемые ОС: Windows, macOS, Linux.',
    category: 'faq',
    department: 'IT-отдел',
    author: 'Козлов Д.В.',
    status: 'active',
    viewCount: 2145,
    downloadCount: 45,
    fileType: 'link',
    tags: ['VPN', 'удалённая работа', 'настройка'],
    updatedAt: '2026-02-10T10:00:00Z',
    createdAt: '2025-03-20T10:00:00Z',
    source1C: 'FAQ.IT',
  },
  {
    id: 'doc-7',
    title: 'Регламент командировочных расходов',
    description:
      'Правила оформления командировок, перечень компенсируемых расходов и порядок отчётности.',
    category: 'regulations',
    department: 'Бухгалтерия',
    author: 'Волкова Н.И.',
    status: 'active',
    viewCount: 456,
    downloadCount: 178,
    fileType: 'pdf',
    fileSize: '890 КБ',
    tags: ['командировки', 'расходы', 'бухгалтерия'],
    updatedAt: '2026-01-28T10:00:00Z',
    createdAt: '2025-04-10T10:00:00Z',
    source1C: 'Документооборот.Регламенты',
  },
  {
    id: 'doc-8',
    title: 'Шаблон коммерческого предложения',
    description:
      'Фирменный шаблон КП с актуальным брендингом. Включает инструкцию по заполнению и примеры.',
    category: 'templates',
    department: 'Отдел продаж',
    author: 'Сидорова Л.К.',
    status: 'active',
    viewCount: 523,
    downloadCount: 289,
    fileType: 'pptx',
    fileSize: '2.8 МБ',
    tags: ['КП', 'продажи', 'презентация'],
    updatedAt: '2026-02-14T10:00:00Z',
    createdAt: '2025-08-20T10:00:00Z',
    source1C: 'Шаблоны.Продажи',
  },
  {
    id: 'doc-9',
    title: 'Инструкция по заполнению табеля',
    description:
      'Руководство по корректному заполнению табеля учёта рабочего времени в системе 1С:ЗУП.',
    category: 'instructions',
    department: 'HR-отдел',
    author: 'Петрова М.С.',
    status: 'active',
    viewCount: 345,
    downloadCount: 67,
    fileType: 'pdf',
    fileSize: '1.5 МБ',
    tags: ['табель', '1С:ЗУП', 'рабочее время'],
    updatedAt: '2026-02-05T10:00:00Z',
    createdAt: '2025-07-12T10:00:00Z',
    source1C: 'Инструкции.HR',
  },
  {
    id: 'doc-10',
    title: 'Как заказать канцелярию?',
    description:
      'Порядок оформления заявки на канцелярские принадлежности через внутренний портал.',
    category: 'faq',
    department: 'АХО',
    author: 'Морозова Т.В.',
    status: 'active',
    viewCount: 789,
    downloadCount: 12,
    fileType: 'link',
    tags: ['канцелярия', 'заявка', 'АХО'],
    updatedAt: '2025-12-15T10:00:00Z',
    createdAt: '2025-05-01T10:00:00Z',
    source1C: 'FAQ.АХО',
  },
  {
    id: 'doc-11',
    title: 'Политика обработки персональных данных',
    description:
      'Документ регламентирует сбор, хранение, обработку и передачу персональных данных сотрудников и клиентов.',
    category: 'policies',
    department: 'Юридический отдел',
    author: 'Смирнова Е.А.',
    status: 'active',
    viewCount: 934,
    downloadCount: 56,
    fileType: 'pdf',
    fileSize: '1.8 МБ',
    tags: ['персональные данные', '152-ФЗ', 'конфиденциальность'],
    updatedAt: '2026-01-20T10:00:00Z',
    createdAt: '2024-06-01T10:00:00Z',
    source1C: 'Политики.ПДн',
  },
  {
    id: 'doc-12',
    title: 'Шаблон акта выполненных работ',
    description: 'Типовая форма акта для закрытия работ по договорам подряда и оказания услуг.',
    category: 'templates',
    department: 'Бухгалтерия',
    author: 'Волкова Н.И.',
    status: 'active',
    viewCount: 412,
    downloadCount: 298,
    fileType: 'xlsx',
    fileSize: '78 КБ',
    tags: ['акт', 'бухгалтерия', 'закрывающие'],
    updatedAt: '2026-01-10T10:00:00Z',
    createdAt: '2025-03-15T10:00:00Z',
    source1C: 'Шаблоны.Бухгалтерия',
  },
  {
    id: 'doc-13',
    title: 'Чек-лист первого дня',
    description:
      'Пошаговый чек-лист для первого рабочего дня нового сотрудника. Помогает ничего не забыть.',
    category: 'onboarding',
    department: 'HR-отдел',
    author: 'Петрова М.С.',
    status: 'active',
    viewCount: 534,
    downloadCount: 267,
    fileType: 'pdf',
    fileSize: '320 КБ',
    tags: ['чек-лист', 'первый день', 'новичок'],
    updatedAt: '2026-02-28T10:00:00Z',
    createdAt: '2025-11-01T10:00:00Z',
    source1C: 'Онбординг.ЧекЛисты',
  },
  {
    id: 'doc-14',
    title: 'Инструкция по работе с CRM',
    description:
      'Полное руководство по работе в CRM-системе: ведение сделок, контактов, задач и отчётов.',
    category: 'instructions',
    department: 'Отдел продаж',
    author: 'Сидорова Л.К.',
    status: 'active',
    viewCount: 423,
    downloadCount: 156,
    fileType: 'pdf',
    fileSize: '4.2 МБ',
    tags: ['CRM', 'продажи', 'сделки'],
    isNew: true,
    updatedAt: '2026-03-09T10:00:00Z',
    createdAt: '2026-02-20T10:00:00Z',
    source1C: 'Инструкции.CRM',
  },
  {
    id: 'doc-15',
    title: 'Как оформить больничный?',
    description:
      'Алгоритм действий при оформлении больничного листа — от уведомления руководителя до получения выплат.',
    category: 'faq',
    department: 'HR-отдел',
    author: 'Петрова М.С.',
    status: 'active',
    viewCount: 1567,
    downloadCount: 23,
    fileType: 'link',
    tags: ['больничный', 'ЛН', 'выплаты'],
    updatedAt: '2026-01-05T10:00:00Z',
    createdAt: '2025-02-10T10:00:00Z',
    source1C: 'FAQ.HR',
  },
];

export const KB_STATS: KBStats = {
  totalDocuments: 139,
  categories: 6,
  updatedThisMonth: 18,
};
